### ISSUE TITLE
Add support to Redmine 2.6

### ISSUE THREAD

**Issue by lucalenardi** [maxrossello/redmine_summed_fields#9]
Hello.

Any plan to support 2.6? At the moment whenever editing a parent task from the issues list, it returns the following error:

```
Started GET "/redmine/issues/490/edit" for xxx.xxx.x.xx at 2015-01-09 00:16:44 +0100
Processing by IssuesController#edit as HTML
  Parameters: {"id"=>"490"}
  Current user: (id=19)
Completed 500 Internal Server Error in 23.0ms

NoMethodError (undefined method `[]' for nil:NilClass):
  app/controllers/issues_controller.rb:395:in `update_issue_from_params'
  app/controllers/issues_controller.rb:175:in `edit'
```
To reproduce:

1.  Create a task
2.  Create a subtask of task
3.  In the issues list, right click over task and hit "edit"

Thanks.

**Comment by maxrossello** [comment]
I use it in production, but I confirm this is a bug. Thank you for reporting this
